server:
  port: 88

spring:
  cloud:
    gateway:
      routes:
        - id: gulimall_pms_route
          uri: lb://gulimall-pms
          predicates:
            - Path=/pms/**

        - id: gulimall_oms_route
          uri: lb://gulimall-oms
          predicates:
            - Path=/oms/**

        - id: gulimall_sms_route
          uri: lb://gulimall-sms
          predicates:
            - Path=/sms/**
            -
        - id: gulimall_ums_route
          uri: lb://gulimall-ums
          predicates:
            - Path=/ums/**
            -
        - id: gulimall_wms_route
          uri: lb://gulimall-wms
          predicates:
            - Path=/wms/**



#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: '*'     #\u5141\u8BB8\u6765\u6E90\u4E8E\u54EA\u4E2A\u670D\u52A1\u5668\u7684\u8BF7\u6C42\u8DE8\u57DF\uFF08\u524D\u7AEF\u6240\u90E8\u7F72\u670D\u52A1\u5668\uFF09
#            allowedMethods: '*'
#            allowCredentials: true  #\u5141\u8BB8\u643A\u5E26\u81EA\u5B9A\u4E49cookie

#        - id: world_route
#          uri: lb://gulimall-pms   #lb = load balance
#          predicates:
#            - Path=/world
#        - id: hello_route
#          uri: lb://gulimall-oms
#          predicates:
#            - Path=/hello
#          filters:
#            - AddResponseHeader=userzrq,666   #\u6DFB\u52A0\u81EA\u5B9A\u4E49\u7684\u54CD\u5E94\u5934
